services:
  storage-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: storage-service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    ports:
      - "${PORT}:3000"
    volumes:
      - storage_data:/data/storage
    restart: unless-stopped

volumes:
  storage_data:
