name: Container CI - Email Service

on:
  pull_request:
    paths:
      - "email-service/**"
      - ".github/workflows/container-email-service.yml"
  push:
    branches:
      - main
      - staging
    paths:
      - "email-service/**"
      - ".github/workflows/container-email-service.yml"

permissions:
  contents: read

jobs:
  container-build:
    if: ${{ hashFiles('email-service/Dockerfile') != '' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: email-service
          file: email-service/Dockerfile
          push: false
          tags: email-service:ci